# general settings
name: stage2_KEEP
model_type: KEEPModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: VFHQ
    type: VFHQDataset
    dataroot_gt: /mnt/sfs-common/rcfeng/video_face/dataset/VFHQ-512-new
    global_meta_info_file: /mnt/sfs-common/rcfeng/video_face/dataset/global_meta_info.txt
    need_align: true
    normalize: true
    dataroot_meta_info: /mnt/sfs-common/rcfeng/video_face/dataset/meta_info
    io_backend:
      type: disk

    scale: 4
    num_frame: 8
    interval_list: [1, 2, 3, 4, 5, 6]
    random_reverse: true
    use_flip: false
    use_rot: false

    # degradation
    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.7, 0.3]
    blur_x_sigma: [2, 10]
    blur_y_sigma: [2, 10]
    noise_range: [0, 10]
    resize_prob: [0.3, 0.3, 0.4]
    crf_range: [25, 45]
    vcodec: ['libx264', 'h264', 'mpeg4']
    vcodec_prob: [0, 1, 0]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: vfhq
    type: VideoRecurrentTestDataset
    dataroot_gt: /mnt/sfs-common/rcfeng/video_face/VFHQ-Test/GT/Interval1_512x512_LANCZOS4
    dataroot_lq: /mnt/sfs-common/rcfeng/video_face/VFHQ-Test/Blind-LR/BlindLR_128x128_easy_Blur5-10_Noise0-10_CRF18-25
    global_meta_info_file: /mnt/sfs-common/rcfeng/video_face/VFHQ-Test/GT/global_meta_info.txt

    need_align: true
    normalize: true
    dataroot_meta_info: /mnt/sfs-common/rcfeng/video_face/VFHQ-Test/meta_info
    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed
    interval: 15

# network structures
network_g:
  type: KEEP
  img_size: 512
  nf: 64
  emb_dim: 256
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 1024
  ch_mult: [1, 2, 2, 4, 4, 8]
  cft_list: []
  cfa_list: []
  fix_modules: ['generator', 'quantize', 'flownet', 'cft', 'hq_encoder']
  flownet_path: weights/GMFlow/gmflow_sintel-0c07dcb3.pth
  kalman_attn_head_dim: 48
  num_uncertainty_layers: 3
  cond: 0
  vqgan_path: experiments/stage1_VQGAN_sz32_code1024/models/net_g_latest.pth

 # this config is needed if no pre-calculated latent
network_vqgan:
  type: VQHQEncoder
  img_size: 512
  nf: 64
  ch_mult: [1, 2, 2, 4, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024
  model_path: experiments/stage1_VQGAN_sz32_code1024/models/net_g_latest.pth # must be same as "vqgan_path" above.
  params: params_ema

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  param_key_g: params_ema
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  use_hq_feat_loss: true
  feat_loss_weight: 1.0
  cross_entropy_loss: true
  entropy_loss_weight: 0.5

  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29517

find_unused_parameters: false
